#!/usr/bin/env bash
# `SHIP_SUBSTANTIVE` and `SHIP_LANDED_BY`: the chain that decides whether a
# round landed. Ship grades every review row itself, above the host seam, so a
# quota notice refuses the round on every host alike (#155, #268): a row with a
# body is a round unless the body is only a refusal notice, and a row with no
# body is a round only when it is a verdict, `approved` or `changes`. Pure jq
# over review rows; no call in this file reaches a host.
#
# The cases below hold `is_notice` at both edges, because a match that is too
# wide drops a real round (the run then waits out its whole poll window) and one
# that is too narrow reproduces #155: PR #154's notice arrived wrapped and with
# a generated footer as well as on one line.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 2
source tests/lib.sh
source skills/ship/scripts/_lib.sh
SHIP_OWNER=o SHIP_REPO=r
source skills/ship/scripts/host/github.sh

notice='Copilot was unable to review this pull request because the user who requested the review has reached their quota limit.'
bot='copilot-pull-request-reviewer[bot]'

# review <id> <sha> <at> <body> [<state>]: one raw GitHub review object.
review() {
  jq -n --arg id "$1" --arg sha "$2" --arg at "$3" --arg b "$4" --arg st "${5:-COMMENTED}" --arg l "$bot" \
    '{id: ($id | tonumber), user: {login: $l}, state: $st,
      body: $b, submitted_at: $at, commit_id: $sha}'
}
# project <head-sha> <review>...: the adapter's call, then Ship's grading,
# the order poll-pr applies them in.
project() {
  local sha=$1; shift
  jq -s --arg sha "$sha" --argjson full '[]' "$_gh_reviews_projection" <<<"$*" | jq "$SHIP_SUBSTANTIVE"
}
# landed <normalised-login> <since> <projection>: poll-pr's landing rules.
landed() { jq -r --arg l "$1" --arg s "$2" "$SHIP_LANDED_BY" <<<"$3"; }
# grade <body> [<state>]: the rule's answer for one row, a host-neutral one
# carrying a `substantive` the rule must overwrite rather than read.
grade() {
  jq -cn --arg b "$1" --arg st "${2:-comment}" \
    '{id: "1", login: "r", state: $st, substantive: "stale", submitted_at: null, body: $b} as $r
     | {on_head: [$r], all: [$r], total: 1}' \
    | jq -r "$SHIP_SUBSTANTIVE"' | [.on_head[0].substantive, .all[0].substantive] | map(tostring) | unique | join(" ")'
}

head=abc123
notice_round=$(project $head "$(review 1 $head 2026-09-14T09:00:00Z "$notice")")
real_round=$(project $head "$(review 2 $head 2026-09-14T09:00:00Z 'Reviewed 3 files. One finding in poll-pr.sh.')")

check "the GitHub adapter no longer grades its rows" false \
  "$(jq -s --arg sha $head --argjson full '[]' "$_gh_reviews_projection" \
       <<<"$(review 1 $head 2026-09-14T09:00:00Z "$notice")" \
     | jq '[.on_head[], .all[]] | any(has("substantive"))')"

check "a notice-only body is not substantive" false "$(grade "$notice")"

check "a notice row still carries its body, so the run can see why it waited" \
  "$notice" "$(jq -r '.on_head[0].body' <<<"$notice_round")"

check "a notice row still appears in on_head[] and all[]" \
  "1 1" "$(jq -r '[(.on_head | length), (.all | length)] | join(" ")' <<<"$notice_round")"

check "a real round is substantive" true "$(jq -r '.on_head[0].substantive' <<<"$real_round")"

# A reviewer's reply to one thread posts as a bodiless comment row of its own:
# counting it lands round 2 off round 1.
check "a bodiless comment row is not substantive" false "$(grade '')"

# A bodiless verdict is the reviewer's whole answer: a GitHub approval with no
# text, or an Azure DevOps vote, which the host records as state alone.
check "a bodiless approved row is substantive" true "$(grade '' approved)"
check "a bodiless changes row is substantive" true "$(grade '' changes)"

long=$(printf '%2000s' '' | tr ' ' x)
check "a clipped long body is substantive" true "$(grade "$long
...[truncated]")"

# Too narrow reproduces #155: the same notice, three shapes it has arrived in.
check "a notice wrapped across lines is still a notice" false \
  "$(grade 'Copilot was unable to review this pull request
because the user has reached their quota limit.')"

check "a notice with a generated footer is still a notice" false \
  "$(grade "$notice
<!-- generated by the reviewer -->")"

check "a notice quoted and bolded is still a notice" false \
  "$(grade '> **Copilot was unable to review this pull request.**')"

check "a notice with its next-review sentence is still a notice" false \
  "$(grade "$notice Next included review is in 3 days.")"

# A notice is a notice whatever verdict the host filed it under.
check "a notice under an approved state is still a notice" false "$(grade "$notice" approved)"

# Too wide drops a real round: the vocabulary must match the refusal, not the
# bare noun, or a finding that names a quota costs the run its poll window.
check "a one-line finding that names a quota is a round" true \
  "$(grade 'The retry should back off rather than burn the API quota.')"

check "a one-line finding that names a rate limit is a round" true \
  "$(grade 'Consider backing off when the API returns a rate limit.')"

check "a body that mentions a quota among real findings is substantive" true \
  "$(grade 'Reviewed 3 files.
The retry should back off rather than burn the API quota.')"

check "a structured round is a round" true \
  "$(grade '### Changes recommended

Unresolved moderate findings affect docs. One finding in poll-pr.sh.')"

check "the head rule cannot land off a notice row" \
  null "$(landed copilot-pull-request-reviewer '' "$notice_round")"

check "the since rule cannot land off a notice row" \
  null "$(landed copilot-pull-request-reviewer 2026-09-14T08:00:00Z "$notice_round")"

check "the head rule still lands a real round" \
  head "$(landed copilot-pull-request-reviewer '' "$real_round")"

check "the since rule still lands a real round" \
  since "$(landed copilot-pull-request-reviewer 2026-09-14T08:00:00Z "$real_round")"

check "a real round on the same head lands past a notice row" \
  head "$(landed copilot-pull-request-reviewer '' \
    "$(project $head "$(review 1 $head 2026-09-14T09:00:00Z "$notice")" \
                      "$(review 2 $head 2026-09-14T09:30:00Z 'Reviewed 3 files. One finding.')")")"

check "a GitHub bodiless approval lands" \
  since "$(landed copilot-pull-request-reviewer 2026-09-14T08:00:00Z \
    "$(project $head "$(review 3 $head 2026-09-14T09:00:00Z '' APPROVED)")")"

finish
