#!/usr/bin/env bash
# `_gh_reviews_projection` and `SHIP_LANDED_BY`: the chain that decides whether
# a round landed. A review whose body is only a quota notice refuses the round
# rather than delivering it, so it is `substantive: false` and neither landing
# rule can land off it (issue #155). Pure jq over review objects; no call in
# this file reaches a host.
#
# The cases below hold `is_notice` at both edges, because a match that is too
# wide drops a real round (the run then waits out its whole poll window) and one
# that is too narrow reproduces #155: PR #154's notice arrived wrapped and with
# a generated footer as well as on one line.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 2
source tests/lib.sh
source skills/ship/scripts/_lib.sh
SHIP_OWNER=o SHIP_REPO=r
source skills/ship/scripts/host/github.sh

notice='Copilot was unable to review this pull request because the user who requested the review has reached their quota limit.'
bot='copilot-pull-request-reviewer[bot]'

# review <id> <sha> <at> <body>: one raw GitHub review object.
review() {
  jq -n --arg id "$1" --arg sha "$2" --arg at "$3" --arg b "$4" --arg l "$bot" \
    '{id: ($id | tonumber), user: {login: $l}, state: "COMMENTED",
      body: $b, submitted_at: $at, commit_id: $sha}'
}
# project <head-sha> <review>...: the adapter's call, in isolation.
project() { local sha=$1; shift; jq -s --arg sha "$sha" --argjson full '[]' "$_gh_reviews_projection" <<<"$*"; }
# landed <normalised-login> <since> <projection>: poll-pr's landing rules.
landed() { jq -r --arg l "$1" --arg s "$2" "$SHIP_LANDED_BY" <<<"$3"; }
# substantive <body>: the flag the projection puts on a row carrying that body.
substantive() { jq -r '.on_head[0].substantive' <<<"$(project h "$(review 1 h 2026-09-14T09:00:00Z "$1")")"; }

head=abc123
notice_round=$(project $head "$(review 1 $head 2026-09-14T09:00:00Z "$notice")")
real_round=$(project $head "$(review 2 $head 2026-09-14T09:00:00Z 'Reviewed 3 files. One finding in poll-pr.sh.')")

check "a notice row is not substantive" false "$(substantive "$notice")"

check "a notice row still carries its body, so the run can see why it waited" \
  "$notice" "$(jq -r '.on_head[0].body' <<<"$notice_round")"

check "a notice row still appears in on_head[] and all[]" \
  "1 1" "$(jq -r '[(.on_head | length), (.all | length)] | join(" ")' <<<"$notice_round")"

check "a real round is unchanged" true "$(jq -r '.on_head[0].substantive' <<<"$real_round")"

check "an empty body is still not a round" false "$(substantive '')"

# Too narrow reproduces #155: the same notice, three shapes it has arrived in.
check "a notice wrapped across lines is still a notice" false \
  "$(substantive 'Copilot was unable to review this pull request
because the user has reached their quota limit.')"

check "a notice with a generated footer is still a notice" false \
  "$(substantive "$notice
<!-- generated by the reviewer -->")"

check "a notice quoted and bolded is still a notice" false \
  "$(substantive '> **Copilot was unable to review this pull request.**')"

check "a notice with its next-review sentence is still a notice" false \
  "$(substantive "$notice Next included review is in 3 days.")"

# Too wide drops a real round: the vocabulary must match the refusal, not the
# bare noun, or a finding that names a quota costs the run its poll window.
check "a one-line finding that names a quota is a round" true \
  "$(substantive 'The retry should back off rather than burn the API quota.')"

check "a one-line finding that names a rate limit is a round" true \
  "$(substantive 'Consider backing off when the API returns a rate limit.')"

check "a multi-line round that mentions a quota is a round" true \
  "$(substantive 'Reviewed 3 files.
The retry should back off rather than burn the API quota.')"

check "a structured round is a round" true \
  "$(substantive '### Changes recommended

Unresolved moderate findings affect docs. One finding in poll-pr.sh.')"

check "the head rule cannot land off a notice row" \
  null "$(landed copilot-pull-request-reviewer '' "$notice_round")"

check "the since rule cannot land off a notice row" \
  null "$(landed copilot-pull-request-reviewer 2026-09-14T08:00:00Z "$notice_round")"

check "the head rule still lands a real round" \
  head "$(landed copilot-pull-request-reviewer '' "$real_round")"

check "the since rule still lands a real round" \
  since "$(landed copilot-pull-request-reviewer 2026-09-14T08:00:00Z "$real_round")"

check "a real round on the same head lands past a notice row" \
  head "$(landed copilot-pull-request-reviewer '' \
    "$(project $head "$(review 1 $head 2026-09-14T09:00:00Z "$notice")" \
                      "$(review 2 $head 2026-09-14T09:30:00Z 'Reviewed 3 files. One finding.')")")"

finish
